import{a as v,S,i}from"./assets/vendor-DRgUjrIE.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",R="51404682-5edc27993faaf387ba494caba";async function u(s,t=1){const o={key:R,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await v.get(q,{params:o})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),B=new S(".gallery a");function h(s){const t=s.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){f.innerHTML=""}function y(){p.classList.remove("is-hidden")}function g(){p.classList.add("is-hidden")}function L(){m.classList.remove("is-hidden")}function w(){m.classList.add("is-hidden")}const b=document.querySelector(".form"),P=b.querySelector('input[name="search-text"]'),$=document.querySelector(".load-more");let a=1,n="",d=0;b.addEventListener("submit",async s=>{if(s.preventDefault(),n=P.value.trim(),!n){i.error({message:"Please enter a search term!",position:"topRight"});return}a=1,M(),w(),y();try{const t=await u(n,a);d=t.totalHits,t.hits.length===0?i.info({message:"Sorry, no images found. Try again!",position:"topRight"}):(h(t.hits),d>15&&L())}catch{i.error({message:"Error fetching images",position:"topRight"})}finally{g()}});$.addEventListener("click",async()=>{a+=1,y(),w();try{const s=await u(n,a);h(s.hits);const t=Math.ceil(d/15);a<t?L():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}catch{i.error({message:"Failed to load more images",position:"topRight"})}finally{g()}});
//# sourceMappingURL=index.js.map
